# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [4]:
print(np.__version__,np.show_config)

1.23.3 <function show at 0x0000022C11C9E4D0>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [5]:
nulvectors = np.zeros(10 ,dtype = int)

In [6]:
nulvectors

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [12]:
print("%d size" % nulvectors.size)
print("%d size of an element in bytes" % nulvectors.itemsize)
print("%d bytes"% (nulvectors.size*nulvectors.itemsize))

10 size
4 size of an element in bytes
40 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [14]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [15]:
a = np.zeros(10,dtype =int )
a[4]=1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [16]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [17]:
b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [18]:
matrix3_3 = np.arange(0,9).reshape(3,3)

In [19]:
print(matrix3_3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [20]:
non_zero = np.array([1,2,0,0,4,0])
np.nonzero(non_zero)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [21]:
dia = np.eye(3,3,dtype="i",k=0)
print(dia)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [2]:
from numpy import random
ra_num = random.random(size=(3,3,3))
ra_num

array([[[0.78140286, 0.44541009, 0.7956388 ],
        [0.08647916, 0.30342106, 0.22270204],
        [0.72176639, 0.79190485, 0.60076007]],

       [[0.23330033, 0.76600567, 0.25930544],
        [0.49861608, 0.45545718, 0.4461024 ],
        [0.298218  , 0.23010604, 0.2347745 ]],

       [[0.30655786, 0.26323276, 0.34206591],
        [0.75067233, 0.23642019, 0.70996961],
        [0.39481868, 0.25284563, 0.44849021]]])

In [5]:
ra_num = random.random(27).reshape(3,3,3)
ra_num

array([[[0.49369833, 0.23996761, 0.73224051],
        [0.51776736, 0.25238845, 0.75618338],
        [0.36642745, 0.21241965, 0.80541056]],

       [[0.2745236 , 0.8579555 , 0.14419879],
        [0.43695568, 0.37195925, 0.08875983],
        [0.38530153, 0.42668961, 0.45951951]],

       [[0.28234817, 0.20796198, 0.34445841],
        [0.5739355 , 0.38982753, 0.43053209],
        [0.3551761 , 0.7933813 , 0.86541513]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [9]:
matrix10 = random.randint(2,100,size=(10,10))

In [11]:
print("%d is maximum" %matrix10.max())
print("%d is minimum" %matrix10.min())

99 is maximum
2 is minimum


In [14]:
matrix11  = random.rand(10,10)
print("%f is maximum" %matrix11.max())
print("%f is minimum" %matrix11.min())

0.990041 is maximum
0.006016 is minimum


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [26]:
mean_arr = random.randint(100,size=30)
mean_arr

array([88,  0, 10, 52, 63, 62, 32, 53,  2, 98, 67, 11,  6, 96, 15, 64, 85,
       11, 72, 97, 36, 17, 36, 86, 12, 74, 55,  7, 77, 84])

In [27]:
print(mean_arr.mean())

48.93333333333333


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [10]:
import numpy as np
#creating a 2 dimensional array with ones.
array = np.ones(20,dtype = int)
#shape to 2 dimensional
a = array.reshape(4,5)
print("original array :\n",a)
#converting the certain elements inside to zeros
a[1:-1, 1:-1] = 0
print("modified :\n",a)


original array :
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
modified :
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [11]:
np.pad(a,(1,1),mode='constant',constant_values = (0,0))

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [17]:
arr = np.arange(1,26).reshape(5,5)
print("original array:\n",arr)
np.pad(arr,(1,1),'constant',constant_values=(0,0))

original array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  0],
       [ 0,  6,  7,  8,  9, 10,  0],
       [ 0, 11, 12, 13, 14, 15,  0],
       [ 0, 16, 17, 18, 19, 20,  0],
       [ 0, 21, 22, 23, 24, 25,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [18]:
arr=[0,1,2,3,4]
np.diag(arr)

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [31]:
arr = np.ones((8,8),dtype=int)
print("original array :\n",arr)
arr[::2,1::2] = 0
arr[1::2,::2] = 0
arr

original array :
 [[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [2]:
import numpy as np
arr = np.zeros((8,8),dtype = int)
print("orginal arr:\n",arr)
arr[::2,::2]=1
arr[1::2,1::2]=1
arr

orginal arr:
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [4]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [6]:
arr = [[0,1],[1,0]]
np.tile(arr,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [9]:
arr = np.random.random((5,5))
# arrmax,arrmin = arrmax(),arrmin()
normal_arr = (arr - arr.min())/(arr.max() - arr.min())
print(normal_arr)

[[0.35866869 0.         0.00680962 0.95893339 0.31824841]
 [0.49971653 0.30768382 0.31236474 0.23526553 0.65281337]
 [0.76601658 0.71930933 0.76550349 0.68103745 0.20194316]
 [0.5614417  0.36568228 0.33106557 0.09793609 0.3138011 ]
 [0.76271732 0.97812861 0.0554648  0.1882358  1.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [14]:
color = np.dtype([("R", np.ubyte,(1,)),
                  ("G", np.ubyte, (1,)),
                  ("B", np.ubyte, (1,)),
                  ("A", np.ubyte, (1,))])
print(color)

[('R', 'u1', (1,)), ('G', 'u1', (1,)), ('B', 'u1', (1,)), ('A', 'u1', (1,))]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [22]:
a = np.matrix(' 3 2 1 ; 2 2 1 ; 4 5 6 ; 5 6 4 ; 9 8 5')
b = np.matrix('1 2 ; 3 4 ; 5 6')
np.dot(a,b)


matrix([[14, 20],
        [13, 18],
        [49, 64],
        [43, 58],
        [58, 80]])

In [24]:
dot = np.dot(np.ones((5,3),int)*4,np.ones((3,2),int)*4)
print(dot)

[[48 48]
 [48 48]
 [48 48]
 [48 48]
 [48 48]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
arr = np.arange(0,15) 

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),axis=-1))
```

In [25]:
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

In [ ]:
Z<Z>Z #not legal

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [1]:
import numpy as np
np.array(0) / np.array(0)

C:\Users\Thamizhiniyan\AppData\Local\Temp\ipykernel_4964\1456380073.py:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [2]:
np.array(0) // np.array(0)

C:\Users\Thamizhiniyan\AppData\Local\Temp\ipykernel_4964\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [3]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [8]:
import numpy as np
z = np.random.uniform(-3,3, size= 10)  #1d of -5 to 5 of random elements
print(z)
a = np.abs(z)
print(a)
c = np.ceil(a)
print(c)

[ 2.95508245 -2.04962291  0.50596783 -0.4324204  -0.81434952  0.70517977
 -0.48555066 -0.14711439 -1.88320003 -2.36926991]
[2.95508245 2.04962291 0.50596783 0.4324204  0.81434952 0.70517977
 0.48555066 0.14711439 1.88320003 2.36926991]
[3. 3. 1. 1. 1. 1. 1. 1. 2. 3.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [11]:
a = np.array([2,3,4,5,6,9])
b = np.array([5,4,21,3,4])
common = np.intersect1d(a,b,assume_unique = True,return_indices = True)
common

(array([3, 4, 4, 5]),
 array([1, 2, 7, 3], dtype=int64),
 array([3, 1, 4, 0], dtype=int64))

In [12]:
a = np.array([2,3,4,5,6,9])
b = np.array([5,4,21,3,4])
com = np.intersect1d(a,b)
com

array([3, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [13]:
data = np.random.random(1000).reshape(10, 10,10) * np.nan
np.nanmedian(data, axis=[1, 2])
# np.seterr(all = "ignore")

C:\Users\Thamizhiniyan\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1217: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [3]:
data = np.random.random(1000).reshape(10, 10,10) * np.nan
np.seterr(all = "ignore")
np.nanmedian(data, axis=[1, 2])

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [20]:
np.sqrt(-1) 

nan

In [21]:
 np.emath.sqrt(-1)

1j

In [22]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [4]:
today = np.datetime64("2022-12-18")
print(today)
yesterday = today -1
print(yesterday)
tomorrow = today + 1
print(tomorrow)


2022-12-18
2022-12-17
2022-12-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [31]:
july_date = np.arange("2016-07","2016-08-01",dtype = 'datetime64[D]')
print(july_date)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [2]:
import numpy as np
arr1 = np.array([2,3,4],dtype = float)
arr2 = np.array([4,5,6],dtype = float)
print("addition:\n",np.add(arr1,arr2,out=arr2))
print("division:\n",np.divide(arr1,2,out = arr1))
print("negative:\n",np.negative(arr1,out = arr1))
print("equation output:\n",np.multiply(arr1,arr2))

addition:
 [ 6.  8. 10.]
division:
 [1.  1.5 2. ]
negative:
 [-1.  -1.5 -2. ]
equation output:
 [ -6. -12. -20.]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [6]:
arr = np.random.rand(1)
print(arr,"\n")
ceil_value = np.ceil(arr)
print("ceil_value",ceil_value,"\n")
floor_value = np.floor(arr)
print("floo4_value",floor_value,"\n")
trunc_value =np.trunc(arr)
print("tunc_value",trunc_value,"\n")
print(arr -arr %1 ,"\n")
astype_=arr.astype(int)
print("astype_value",astype_)


[0.596556] 

ceil_value [1.] 

floo4_value [0.] 

tunc_value [0.] 

[0.] 

astype_value [0]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [11]:
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [6]:
def generate():
    for i in range(10):
        yield i
Z = np.fromiter(generate(),dtype=float,count=-1) # -1 all the elements in the iteration is read
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [9]:
a = np.linspace(0,1,11,endpoint=False) # false i.e is avoid 1 being read
a[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [42]:
state = np.random.seed(23)
A=np.random.randint(0,10,10)
A.sort(-1)
A

array([3, 3, 6, 6, 6, 7, 8, 8, 9, 9])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [24]:
A = np.array([1,2,3,4]).reshape(2,2)
print(np.add.reduce(A,1))
B =  np.array([1,2,3,4])
print(np.add.reduce(B))

[3 7]
10


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [43]:
A = np.random.random((1,4))
B = np.random.random((1,4))
print(np.array_equal(A,B))
print(np.allclose(A,B))

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [1]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1
# A = np.array([1,2,3])
# A.flags.writeable() = False
# A[2]=4

NameError: name 'np' is not defined

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [52]:
C_C = np.random.random((10,2))
X = C_C[:,0] # seprate the cordinates x- coordinates
Y = C_C[:,1] # y- cordinates
# r=√x2+y2
Sqr = np.sqrt(X**2+Y**2)
# tan−1(yx)
tan = np.arctan2(Y,X)
print("r=√x2+y2 \nr= ",Sqr)
print()
print("tan−1(yx)\ntan-1 =",tan)

r=√x2+y2 
r=  [1.14654907 1.01271251 0.64933752 0.8805237  0.59170261 1.07404842
 0.86344786 0.51168191 1.29302265 0.44777294]

tan−1(yx)
tan-1 = [0.93041587 0.21397595 0.31309665 0.3965784  1.51372967 0.45600337
 0.23837475 1.27125866 0.70779181 1.50744783]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [55]:
A=np.arange(10)
arg_max = np.argmax(A)
print(arg_max)
A[arg_max]=0
print(A)

9
[0 1 2 3 4 5 6 7 8 0]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [67]:
a = np.zeros((10,10),[("x",float),("y",float)])
a["x"],a["y"] = np.meshgrid(np.linspace(0,1,10),
                            np.linspace(0,1,10))
print(a)
print(a["x"])
print(a["y"])
print(a[0])

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [69]:
x=np.array([1,2,3,4,5])
y=np.array([3,6,5,3])
# Cij =1/(xi - yj)
#i is row hence x as only one row reshaped
c= 1.0/(x.reshape(5,1) - y)
c

array([[-0.5       , -0.2       , -0.25      , -0.5       ],
       [-1.        , -0.25      , -0.33333333, -1.        ],
       [        inf, -0.33333333, -0.5       ,         inf],
       [ 1.        , -0.5       , -1.        ,  1.        ],
       [ 0.5       , -1.        ,         inf,  0.5       ]])

In [70]:
c=1.0/np.subtract.outer(x,y)
c

array([[-0.5       , -0.2       , -0.25      , -0.5       ],
       [-1.        , -0.25      , -0.33333333, -1.        ],
       [        inf, -0.33333333, -0.5       ,         inf],
       [ 1.        , -0.5       , -1.        ,  1.        ],
       [ 0.5       , -1.        ,         inf,  0.5       ]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [77]:
for dtype in [np.int8, np.int32, np.int64]:
   print("min :",np.iinfo(dtype).min)
   print("max :",np.iinfo(dtype).max)
print()
for dtype in [np.float32, np.float64]:
   print("min :",np.finfo(dtype).min)
   print("max :",np.finfo(dtype).max)
   print("eps :",np.finfo(dtype).eps)

min : -128
max : 127
min : -2147483648
max : 2147483647
min : -9223372036854775808
max : 9223372036854775807

min : -3.4028235e+38
max : 3.4028235e+38
eps : 1.1920929e-07
min : -1.7976931348623157e+308
max : 1.7976931348623157e+308
eps : 2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [90]:
np.set_printoptions(threshold = 1000)
np.zeros((30,20))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [113]:
vector = np.arange(100)
print(vector)
scalar = 45
sub = vector - scalar
print(sub)
value = sub.argmin()
print(value)
index = vector[value]
index

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[-45 -44 -43 -42 -41 -40 -39 -38 -37 -36 -35 -34 -33 -32 -31 -30 -29 -28
 -27 -26 -25 -24 -23 -22 -21 -20 -19 -18 -17 -16 -15 -14 -13 -12 -11 -10
  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7   8
   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26
  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44
  45  46  47  48  49  50  51  52  53  54]
0


0

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [133]:
A = np.zeros(3,[("position",[("x",int),("y",int)]),
            ("colour",[("r",float),("g",float),("b",float)])])
print(A)

[((0, 0), (0., 0., 0.)) ((0, 0), (0., 0., 0.)) ((0, 0), (0., 0., 0.))]


In [135]:
print(A["position"])
print()
print(A["colour"])


[(0, 0) (0, 0) (0, 0)]

[(0., 0., 0.) (0., 0., 0.) (0., 0., 0.)]


In [139]:
A[0]

((0, 0), (0., 0., 0.))

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [167]:
np.set_printoptions(precision= 2,threshold = 10000)
c_c = np.random.randint(0,100,size=(10,2))
x,y = np.atleast_2d(c_c[:,0]),np.atleast_2d(c_c[:,1])
# x is 2 dimenionsal array of 0th elements of c_c

### √((x2 – x1)² + (y2 – y1)²).
variables defined below(X2=x ,X1=x.T),(y2=y,y1=y.T)

In [ ]:
X=(x-x.T)**2
Y=(y-y.T)**2
Distance = np.sqrt(X+Y)
Distance

In [159]:
x

array([[99, 91, 59, 66, 82, 25, 45, 98, 86, 85]])

In [160]:
x.T

array([[99],
       [91],
       [59],
       [66],
       [82],
       [25],
       [45],
       [98],
       [86],
       [85]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [189]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32,copy=False)
Z.dtype

dtype('int32')

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
A = np.genfromtxt("missing.csv", delimiter=",")

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [197]:
x=np.arange(0,50,dtype=int).reshape(10,5)
for index,values in np.ndenumerate(x):
    print(index,values)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9
(2, 0) 10
(2, 1) 11
(2, 2) 12
(2, 3) 13
(2, 4) 14
(3, 0) 15
(3, 1) 16
(3, 2) 17
(3, 3) 18
(3, 4) 19
(4, 0) 20
(4, 1) 21
(4, 2) 22
(4, 3) 23
(4, 4) 24
(5, 0) 25
(5, 1) 26
(5, 2) 27
(5, 3) 28
(5, 4) 29
(6, 0) 30
(6, 1) 31
(6, 2) 32
(6, 3) 33
(6, 4) 34
(7, 0) 35
(7, 1) 36
(7, 2) 37
(7, 3) 38
(7, 4) 39
(8, 0) 40
(8, 1) 41
(8, 2) 42
(8, 3) 43
(8, 4) 44
(9, 0) 45
(9, 1) 46
(9, 2) 47
(9, 3) 48
(9, 4) 49


In [223]:
for index in np.ndindex(x.shape):
    print(index,x[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9
(2, 0) 10
(2, 1) 11
(2, 2) 12
(2, 3) 13
(2, 4) 14
(3, 0) 15
(3, 1) 16
(3, 2) 17
(3, 3) 18
(3, 4) 19
(4, 0) 20
(4, 1) 21
(4, 2) 22
(4, 3) 23
(4, 4) 24
(5, 0) 25
(5, 1) 26
(5, 2) 27
(5, 3) 28
(5, 4) 29
(6, 0) 30
(6, 1) 31
(6, 2) 32
(6, 3) 33
(6, 4) 34
(7, 0) 35
(7, 1) 36
(7, 2) 37
(7, 3) 38
(7, 4) 39
(8, 0) 40
(8, 1) 41
(8, 2) 42
(8, 3) 43
(8, 4) 44
(9, 0) 45
(9, 1) 46
(9, 2) 47
(9, 3) 48
(9, 4) 49


In [206]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
#  Z exp ( − (x − µ)2/2σ2 ) 

In [242]:
x,y = np.meshgrid(np.linspace(0,10,10),np.linspace(0,10,10))
distance = np.sqrt(x*x+y*y)
sigma,mu = 1.0 ,0.0
Gaus =np.exp((-(distance-mu)**2/(2*(sigma**2))))
Gaus

array([[1.00e+00, 5.39e-01, 8.47e-02, 3.87e-03, 5.14e-05, 1.99e-07,
        2.23e-10, 7.31e-14, 6.96e-18, 1.93e-22],
       [5.39e-01, 2.91e-01, 4.57e-02, 2.09e-03, 2.77e-05, 1.07e-07,
        1.20e-10, 3.94e-14, 3.75e-18, 1.04e-22],
       [8.47e-02, 4.57e-02, 7.17e-03, 3.27e-04, 4.35e-06, 1.68e-08,
        1.89e-11, 6.19e-15, 5.89e-19, 1.63e-23],
       [3.87e-03, 2.09e-03, 3.27e-04, 1.49e-05, 1.99e-07, 7.68e-10,
        8.64e-13, 2.83e-16, 2.69e-20, 7.46e-25],
       [5.14e-05, 2.77e-05, 4.35e-06, 1.99e-07, 2.64e-09, 1.02e-11,
        1.15e-14, 3.75e-18, 3.58e-22, 9.91e-27],
       [1.99e-07, 1.07e-07, 1.68e-08, 7.68e-10, 1.02e-11, 3.94e-14,
        4.44e-17, 1.45e-20, 1.38e-24, 3.83e-29],
       [2.23e-10, 1.20e-10, 1.89e-11, 8.64e-13, 1.15e-14, 4.44e-17,
        4.99e-20, 1.63e-23, 1.55e-27, 4.31e-32],
       [7.31e-14, 3.94e-14, 6.19e-15, 2.83e-16, 3.75e-18, 1.45e-20,
        1.63e-23, 5.34e-27, 5.09e-31, 1.41e-35],
       [6.96e-18, 3.75e-18, 5.89e-19, 2.69e-20, 3.58e-22, 1.38e-

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [122]:
A = np.arange(6).reshape(2,3)
B = np.arange(7,10).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[ 7  9 11]
 [10 12 14]]


In [126]:
it.operands

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[7, 8, 9]]),
 array([[ 7,  9, 11],
        [10, 12, 14]]))

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)